services:
  db:
    image: docker.io/timescale/timescaledb-ha:pg18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGREST_DB_PASSWORD: ${POSTGREST_DB_PASSWORD}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      RESEARCHER_DB_PASSWORD: ${RESEARCHER_DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./app_data/db:/var/lib/postgresql:z
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:z
      - ./src/db/set_passwords.sh:/docker-entrypoint-initdb.d/99_set_passwords.sh:z
  postgrest:
    image: docker.io/postgrest/postgrest:v14.5
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PGRST_DB_SCHEMAS=api
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_DB_URI=${PGRST_DB_URI}
      - PGRST_JWT_SECRET=${PGRST_JWT_SECRET}
      # - PGRST_JWT_SECRET_IS_BASE64=${PGRST_JWT_SECRET_IS_BASE64}
    ports:
      - "3000:3000"
