// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiListParticipant struct {
	UserID       pgtype.UUID
	Properties   []byte
	SysCreatedAt pgtype.Timestamptz
	SysChangedAt pgtype.Timestamptz
	Username     string
	Role         string
	StudyName    string
	StudyID      int64
}

type ApiListSensor struct {
	ID           int64
	SensorType   string
	Name         pgtype.Text
	Description  pgtype.Text
	Properties   []byte
	CredentialID pgtype.Int8
	SysCreatedAt pgtype.Timestamptz
	LastActivity interface{}
}

type ApiManyParticipantsStudy struct {
	UserID           pgtype.UUID
	StudyID          int64
	MembershipPeriod pgtype.Range[pgtype.Timestamptz]
}

type ApiObservation struct {
	ID             int64
	DataStreamID   int64
	PhenomenonTime pgtype.Range[pgtype.Timestamptz]
	Result         float64
	Properties     []byte
	LocationID     pgtype.Int8
	Geog           interface{}
}

type ApiOwnership struct {
	UserID       pgtype.UUID
	SensorID     int64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	SysCreatedAt pgtype.Timestamptz
}

type ApiParticipant struct {
	UserID       pgtype.UUID
	Properties   []byte
	SysCreatedAt pgtype.Timestamptz
	SysChangedAt pgtype.Timestamptz
}

type ApiSensor struct {
	ID           int64
	SensorType   string
	Name         pgtype.Text
	Description  pgtype.Text
	Properties   []byte
	CredentialID pgtype.Int8
	SysCreatedAt pgtype.Timestamptz
}

type ApiStudy struct {
	ID           int64
	Name         string
	ActivePeriod pgtype.Range[pgtype.Timestamptz]
}

// Any credentials that need to be saved in the database (api keys, ...)
type AuthCredential struct {
	ID          int64
	Description string
	Properties  []byte
}

type AuthUser struct {
	ID           pgtype.UUID
	Username     string
	Password     string
	Role         string
	SysCreatedAt pgtype.Timestamptz
}

type ConfigAppSetting struct {
	SettingValue string
	SettingName  string
}

// Something that the sensor measures (temperature, humidity, speed ...)
type DataDataStream struct {
	ID                int64
	SensorID          pgtype.Int8
	Name              pgtype.Text
	Description       pgtype.Text
	UnitOfMeasurement pgtype.Text
	Properties        []byte
}

// Geographic location where the observation was made
type DataLocation struct {
	ID         int64
	Geog       interface{}
	Properties []byte
}

type DataManyParticipantsStudy struct {
	UserID           pgtype.UUID
	StudyID          int64
	MembershipPeriod pgtype.Range[pgtype.Timestamptz]
}

// Measurement of the datastream
type DataObservation struct {
	ID           int64
	DataStreamID int64
	// The time period when the measurement occurred in the real world.
	PhenomenonTime pgtype.Range[pgtype.Timestamptz]
	// The measured value
	Result     float64
	Properties []byte
	LocationID pgtype.Int8
}

type DataOwnership struct {
	UserID       pgtype.UUID
	SensorID     int64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	SysCreatedAt pgtype.Timestamptz
}

type DataParticipant struct {
	UserID       pgtype.UUID
	Properties   []byte
	SysCreatedAt pgtype.Timestamptz
	SysChangedAt pgtype.Timestamptz
}

// Sensors of any kind, this can be a physical sensor, a mobile phone application, a sensor connected to a mobile phone app (fitbit) ... But, it has to be identifiable
type DataSensor struct {
	ID          int64
	SensorType  string
	Name        pgtype.Text
	Description pgtype.Text
	// custom properties
	Properties   []byte
	CredentialID pgtype.Int8
	SysCreatedAt pgtype.Timestamptz
}

type DataStudy struct {
	ID           int64
	Name         string
	ActivePeriod pgtype.Range[pgtype.Timestamptz]
}

type LogIntegrationExecution struct {
	Name     string
	Datetime pgtype.Timestamptz
	Value    []byte
}

type LogLoginAttempt struct {
	Username     string
	SysCreatedAt pgtype.Timestamptz
	Success      bool
	Properties   []byte
}
