// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDataStream = `-- name: CreateDataStream :one
insert into data.data_streams (
    sensor_id,
    name,
    description,
    unit_of_measurement,
    properties
) values (
    $1,$2,$3,$4,$5
) returning id
`

type CreateDataStreamParams struct {
	SensorID          pgtype.Int8
	Name              pgtype.Text
	Description       pgtype.Text
	UnitOfMeasurement pgtype.Text
	Properties        []byte
}

func (q *Queries) CreateDataStream(ctx context.Context, arg CreateDataStreamParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDataStream,
		arg.SensorID,
		arg.Name,
		arg.Description,
		arg.UnitOfMeasurement,
		arg.Properties,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLocation = `-- name: CreateLocation :one
insert into data.locations (
    geog,
    properties
) values (
    ST_SetSRID(ST_MakePoint($2::float, $3::float), 4326)::geography,$1
) on conflict (geog)
do update set geog = excluded.geog
returning id
`

type CreateLocationParams struct {
	Properties []byte
	Lon        float64
	Lat        float64
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Properties, arg.Lon, arg.Lat)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createObservation = `-- name: CreateObservation :exec
insert into data.observations (
    data_stream_id,
    phenomenon_time,
    result,
    properties,
    location_id
) values (
    $1,$2,$3,$4,$5
) on conflict (data_stream_id, phenomenon_time) do nothing
`

type CreateObservationParams struct {
	DataStreamID   int64
	PhenomenonTime pgtype.Range[pgtype.Timestamptz]
	Result         float64
	Properties     []byte
	LocationID     pgtype.Int8
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) error {
	_, err := q.db.Exec(ctx, createObservation,
		arg.DataStreamID,
		arg.PhenomenonTime,
		arg.Result,
		arg.Properties,
		arg.LocationID,
	)
	return err
}

const getDataStreams = `-- name: GetDataStreams :many
select id, name from data.data_streams eds
where eds.sensor_id = $1
`

type GetDataStreamsRow struct {
	ID   int64
	Name pgtype.Text
}

func (q *Queries) GetDataStreams(ctx context.Context, sensorID pgtype.Int8) ([]GetDataStreamsRow, error) {
	rows, err := q.db.Query(ctx, getDataStreams, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDataStreamsRow
	for rows.Next() {
		var i GetDataStreamsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAtmotubes = `-- name: ListAtmotubes :many
select s.id as sensor_id, (s.properties->>'atmotube_id')::text as atmotube_id, (c.properties->>'api_key')::text as api_key from data.sensors s
left join auth.credentials c on s.credential_id = c.id
where s.sensor_type = 'ATMOTUBE_PRO'
`

type ListAtmotubesRow struct {
	SensorID   int64
	AtmotubeID string
	ApiKey     string
}

func (q *Queries) ListAtmotubes(ctx context.Context) ([]ListAtmotubesRow, error) {
	rows, err := q.db.Query(ctx, listAtmotubes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAtmotubesRow
	for rows.Next() {
		var i ListAtmotubesRow
		if err := rows.Scan(&i.SensorID, &i.AtmotubeID, &i.ApiKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
